setup.py

* Because of reanahub/reana-workflow-engine-yadage#36
we use `yadageschemas=0.7.4`

installation: bump `yadageschemas` to 0.7.4

---

setup.py

* Declares support for Python 2.7 only in `setup.py`. (see #17)

installation: declare Python 2.7 support only

---

reana_client/api/client.py
reana_client/cli/__init__.py
reana_client/cli/analyses.py
reana_client/config.py
reana_client/utils.py

* Add `-f / --file` option to `reana run` command that specifies which
REANA specifications file should be used.
(addresses #14)
* Add `--skip-validation` option to `reana run` command in order to
skip validation of the given specifications file, before submitting
it to Reana Server.
(addresses #19)

cli: pass spec file as parameter `reana run`

---

reana_client/cli/__init__.py
reana_client/cli/analyses.py

* Add `reana validate` command to validate a REANA specification file.
Uses either default value (e.g. .reana.yml) or a file specified with
`-f / --file` -option (e.g. `reana validate -f my-spec-file.yml`).
(closes #19)

cli: add `reana validate` command

---

reana_client/cli/inputs.py

* (closes reanahub/reana-server#13).

cli: activate file seeding

---

docs/gettingstarted.rst
docs/userguide.rst

* Uses ``-workflow`` CLI argument instead of ``--workflow-id``.

docs: fix for ``--workflow`` CLI argument

---

reana_client/api/client.py
reana_client/cli/workflow.py
reana_client/openapi_connections/reana_server.json

* Warns user when there is a conflict changing workflow status such as
starting an already started/finished/failed workflow. (closes #75)

cli: improve workflow start error messages

---

MANIFEST.in
pycharm_click_debug.py

* Removes `pycharm_click_debug.py` file. (closes #86)

global: pycharm click debug removal

---

reana_client/api/client.py
reana_client/cli/analyses.py
reana_client/cli/code.py
reana_client/cli/inputs.py
reana_client/cli/outputs.py
reana_client/cli/workflow.py
reana_client/errors.py
reana_client/utils.py

* Add support for specifying files that should be
uploaded to workflow workspace by absolute paths (closes #67).

cli: support file seeding with absolute paths

---

reana_client/cli/__init__.py
reana_client/cli/status.py

* ADDS `reana-client status` cli command to show current
server, server status and selected workflow.

cli: addition of status command

---

reana_client/cli/cwl_runner.py

(Closes https://github.com/reanahub/reana-workflow-engine-cwl/issues/30 but this wasn't tested with the full conformance tests)

cwl: fix upload file path for test: 99

---

AUTHORS.rst
CHANGES.rst
reana_client/version.py

(To be merged after https://github.com/reanahub/reana-client/pull/79)
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>

release: v0.2.0

---

.travis.yml
reana_client/cli/code.py
reana_client/cli/inputs.py
reana_client/cli/outputs.py
reana_client/cli/workflow.py
reana_client/utils.py
requirements-dev.txt
setup.py

This will require a release of reana-commons

utils: import cli printer from reana-commons

---

reana_client/cli/workflow.py

* ADD step column to show current running step in workflow,
and show Job.prettified_cmd in command column.
Connects https://github.com/reanahub/reana-client/issues/125

cli: workflow status progress columns

---

reana_client/api/client.py
reana_client/cli/workflow.py
reana_client/openapi_connections/reana_server.json

* ADD arbitrary number of parameters in workflow_start().
* Updates the reana-server openapi spec with parameters in
set_workflow_status, and the status passed in the query instead of
the request body.
Connects https://github.com/reanahub/reana-client/issues/21
Closes https://github.com/reanahub/reana-client/issues/143

cli: addition of parameters in workflow_start()

---

reana_client/version.py
setup.py

* Introduces more upper boundary limits for dependencies to make sure all the
client components are installable from PyPI in the future.
(addresses reanahub/reana#80)

installation: more version limits

---

docs/userguide.rst
reana_client/cli/files.py

* Modifies the cli `reana-client download` command to parse the
reana.yaml and download all outputs listed there.
Closes #173 

cli: download all outputs

---

docs/gettingstarted.rst
docs/userguide.rst
reana_client/cli/files.py
reana_client/cli/workflow.py
tests/test_cli_workflows.py

* introducing run command, which wrapps `create`, `upload` & `start`.
Closes #196
* deleting unused imports.

cli: introducing run command

---

reana_client/cli/workflow.py

* Adds flags for overriding input parameters and passing operational
options. Connects #200 

cli: adding -o & -p flags for run command

---

reana_client/api/client.py
setup.py

* Changes start_workflow to call the start_workflow endpoint in RS,
instead of set_workflow_status.
Connects https://github.com/reanahub/reana/issues/119

client: refactor start_workflow

---

reana_client/cli/utils.py
reana_client/cli/workflow.py
setup.py

* Refactors get workflow logs to RWC response, which includes the
logs from the jobs of the workflow.
Closes https://github.com/reanahub/reana-client/issues/218, https://github.com/reanahub/reana-client/issues/217

cli: workflow logs refactoring

---

reana_client/cli/workflow.py

* Adds --json flag in logs command, to print the output in json
format.
Closes #231 

cli: output logs in json format

---

reana_client/cli/workflow.py
reana_client/config.py
tests/test_cli_workflows.py

Closes #295
Adds a flag the start and run workflow commands to follow the
workflow execution until termination.
Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>

cli: add follow flag to workflow execution

---

reana_client/cli/workflow.py
setup.py

* Adds `-w` option as an alias for `-n` to the `create` command
so that users can use `-w` consistently everywhere to specify
the desired workflow.  (Principle of least astonishment.)

cli: create -w

---

docs/userguide.rst
reana_client/cli/secrets.py
reana_client/cli/utils.py
reana_client/utils.py
tests/test_cli_secrets.py

* Change syntax for file and env types (Closes #306)
* Introduce NotRequiredIf functionality for click options (Closes #288)
* Change type of  argument to click.Path for native path support (Closes #294)
* Limit k8s secret name to just basename- it used to fail
because of forbiden characters (Closes #305)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

cli: secrets cli refactor

---

reana_client/utils.py
reana_client/version.py
setup.py

Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

utils: upgraded yadage

---

.travis.yml
setup.py

* Upgrades version of `cwltool` to 1.0.20191022103248 which fixes
installation troubles on Python-3.8 systems.
(addresses reanahub/reana-client#329)

cwltool: 1.0.20191022103248

---

setup.py

* Specifies minimal PyYAML version to 5.1 and above. This fixes a
problem with file upload using Python-2.7.  (closes #301)

installation: PyYAML version boundaries

---

reana_client/cli/workflow.py

* Removes free parameters for the `run` command that were used to upload
source files, since the sources are now always being uploaded from
reana.yaml configuration files. (closes #335)

cli: `run` command without free parameters

---

docs/gettingstarted.rst

* REANA-Cluster is being deprecated so we are removing all references
to it (closes reanahub/reana#238).

docs: remove reana-cluster references

---

reana_client/cli/workflow.py
reana_client/utils.py

* Refactors cwl wf validation to use CLI instead of python api
in order to remove CWL info messages.
Closes #340

utils: refactors cwl validation to remove info messages

---

reana_client/cli/files.py

cli: hide .git related files

---

reana_client/api/client.py
reana_client/cli/__init__.py
reana_client/cli/cwl_runner.py
reana_client/cli/files.py
reana_client/cli/ping.py
reana_client/cli/secrets.py
reana_client/cli/utils.py
reana_client/cli/workflow.py
reana_client/utils.py
tests/test_cli_workflows.py

closes #354 
Optimizations:
* `ping`: ~2.2s → ~0.8s
* `--help`: ~0.6s → ~0.3s
* `version`: ~0.6s → ~0.3s
* `create`: ~2s → ~1.2s
* `start`: ~2.4s → ~1.5s
* `status`: ~1.6s → ~1.2s
* `run`: ~7s → ~3.9s (reana-demo-worldpopulation)
* `list`: ~1.6s → ~1.2s
* `diff`: ~1.6s → ~1s
* `logs`: ~1.6s → ~1s
* `stop`: ~1s → ~0.4s
* `upload`: ~2.3s → ~1.2s
* `download`: ~1.8s → ~1.1s
* `du`: ~1.5s → ~0.9s
* `ls`: ~2s → ~1.6s
* `mv`: ~2.9s → ~2.3s
* `rm`: ~1.6s → ~1s

cli: optimize reana-client

---

reana_client/cli/utils.py
reana_client/cli/workflow.py
reana_client/utils.py
tests/test_cli_workflows.py

* Addresses reanahub/reana-workflow-controller/issues/289

cli: in case of restart returns proper run number

---

.travis.yml
reana_client/cli/workflow.py
setup.py

closes #389 
**Before:**
**After:**

cli: nicer formatting in diff output

---

reana_client/utils.py

closes #387
**Output:**
```console
$ reana-client validate -f reana-yadage.yaml                                        
/Users/marco/code/reanahub/reana-demo-root6-roofit/reana-yadage.yaml is not a valid REANA specification:
{'scheduler_type': 'singlestep-stage', 'parameters': [{'key': 'events', 'value': {'step': 'init', 'output': 'events', 'expression_type': 'stage-output-selector'}}, {'key': 'gendata', 'value': {'step': 'init', 'output': 'gendata', 'expression_type': 'stage-output-selector'}}, {'key': 'outfilename', 'value': '{workdir}/data.root'}], 'step': {'process': {'process_type': 'interpolated-script-cmd', 'script': 'root -b -q \'{gendata}({events},"{outfilename}")\'', 'interpreter': 'sh'}, 'publisher': {'publisher_type': 'frompar-pub', 'outputmap': {'data': 'outfilename'}}, …
```

validate: enrich yadage validation output error

---

reana_client/api/client.py
reana_client/cli/files.py
reana_client/utils.py

Instead of go looking for `reana.yaml` in the current (or parents)
directory to determine the input and output files, take into account
the previously created workflow and retrive its specification to get
this information.
closes #403

cli: upload & download based on saved spec

---

reana_client/cli/files.py
reana_client/cli/utils.py
reana_client/cli/workflow.py
reana_client/schemas/reana_analysis_schema.json
reana_client/utils.py
setup.py

closes #356
`reana.yaml` could be like:
```yaml
version: 0.6.0
[...]
workflow:
type: yadage
file: workflow.yaml
options: 
toplevel: './example'
[...]
```

global: allow operational options in reana.yaml

---

.travis.yml
reana_client/api/client.py
reana_client/version.py
setup.py

This PR addresses an outdated `reana-commons` API reference (issue https://github.com/reanahub/reana-client/issues/417).
In addition I have:
- Bumped up the package version.
- Bumped up the `reana-commons` min. version to ensure it references its updated API.

cli: fix reana-common API ref.

---

AUTHORS.rst
CHANGES.rst
reana_client/cli/workflow.py

closes #415
Generic way to filter the logs according to `step`, `compute_backend`, `docker_img` and `status`. Replaces the current `-s` `--step` option that returns the logs of desired steps.
Use example
```
$ reana-client logs --filter status=failed --filter compute_backend=htcondor
$ reana-client logs --filter step=gendata
```

cli: filter logs

---

.gitignore
MANIFEST.in
run-tests.sh
scripts/generate_cli_api.py

- adds link pointing to full docs (readthedocs)
addresses reanahub/reana#335

docs: revert cli api docs autogeneration

---

reana_client/api/client.py
reana_client/cli/files.py
reana_client/cli/utils.py
reana_client/cli/workflow.py
reana_client/config.py
tests/test_cli_workflows.py

cli: implement filtering by status and search by name

---

CHANGES.rst
reana_client/api/client.py
reana_client/cli/files.py

For compatibility reasons between cluster 0.8.x and client 0.7.x
When quota is already exceeded:
**Before:**
```console
$ reana-client upload -w helloworld LICENSE                                                                                                                                                                              
File /LICENSE was successfully uploaded.       
```
_(even though the file is not uploaded)_
**After:**
```console
$ reana-client upload -w helloworld 800Kfile.dat
Something went wrong while uploading /Users/marco/code/reanahub/reana-demo-helloworld/800Kfile.dat: 
User quota exceeded.
```

cli: fix exception handling on file upload

---

CHANGES.rst
reana_client/cli/__init__.py
reana_client/utils.py
reana_client/version.py

Removes trailing whitespaces, backslahes, new line characters and tabs from user exported `REANA_SERVER_URL`.
Steps to test:
```python
$ reana-client create -w test -f reana-demo-helloworld/reana.yaml
$ export REANA_SERVER_URL=https://localhost:30443// \n
$ reana-client open -w test
https://localhost:30443/token # result
```
closes #453

cli: remove traling slash from reana server url

---

CHANGES.rst
reana_client/config.py
reana_client/utils.py
tests/test_validate_environments.py

closes #457 
closes #382
- To run: `reana-client validate --environments`
- Choose a `reana-demo-*` and play removing environment tags, adding invalid ones, etc.
- Add `kubernetes_uid` to remove warnings for e.g. ATLAS images.

validate: uid/gid environment validation for serial

---

docs/index.rst
reana_client/api/client.py

It would be good to expose also `get_workflow_logs` function in the docs, since it will be used in the blog post

docs: added get_workflow_logs function under rest API docs section

---

CHANGES.rst
reana_client/cli/workflow.py
reana_client/config.py
reana_client/printer.py
reana_client/utils.py
reana_client/validation.py

Paves the way to implement https://github.com/reanahub/reana-client/issues/431
Run `reana-client validate` or `reana-client validate --environments --pull` with any of our examples for any workflow engine.
- To force warnings: e.g. add dangerous operations (`sudo` , `cd /`) to workflow commands, add unused parameters, use undefined parameters..
- To force errors: e.g. modify env images to non-existing ones.

validate: enrich output messages

---

CHANGES.rst
reana_client/cli/workflow.py

Add --exclude-deleted option to hide deleted workflows
Addresses #482

cli: list deleted workflows by default

---

reana_client/api/client.py

closes #494 
closes reanahub/docs.reana.io#23 
Updated Python API ref: https://reana-client--495.org.readthedocs.build/en/495/#module-reana_client.api.client
Working example: https://gist.github.com/mvidalgarcia/a1e61628dd67ed1a8b80d868684e1352

client: allow spec path when creating wf from API

---

CHANGES.rst
reana_client/api/client.py
reana_client/cli/files.py
setup.py
tests/test_cli_files.py

Depends on https://github.com/reanahub/reana-client/pull/483
Needs `r-commons` release to pass - https://github.com/reanahub/reana-commons/pull/253
closes #402
- Create a workflow
- Upload multiple files in multiple levels of directories
- Try to download different directories by name
- Try to download multiple files by passing glob patterns
Pseudo-example
```console
$ reana-client download -w workflow 'mydir'
$ reana-client download -w workflow '**/*.py'
$ reana-client download -w workflow '**/*.txt'
$ reana-client download -w workflow 'mydir/foo/*.py'
...
```
If it the pattern matches more than one file, you should get a zip downloaded, otherwise a single file.
When downloading a single file,  until now, the path where this file is in the workspace is respected locally. This is because …

cli: support dir and glob pattern on download 

---

CHANGES.rst
reana_client/cli/utils.py

Closes #497.
To test:
1. Create a workflow and add some more steps with sleeps, e.g. `reana-demo-helloworld`
```diff
diff --git a/reana.yaml b/reana.yaml
index 50d1bd8..d243815 100644
--- a/reana.yaml
+++ b/reana.yaml
@@ -18,6 +18,12 @@ workflow:
--inputfile "${inputfile}"
--outputfile "${outputfile}"
--sleeptime ${sleeptime}
+      - environment: 'python:2.7-slim'
+        commands:
+          - sleep 5
+      - environment: 'python:2.7-slim'
+        commands:
+          - sleep 20
outputs:
files:
- results/greetings.txt
```
2. Observe `reana-client logs -w workflow-name`

cli: add start and finish time to job logs

---

reana_client/validation.py
tests/conftest.py
tests/test_validate_parameters.py

Fixes user [reported issue](https://forum.reana.io/t/validation-does-not-fail-when-a-parameter-is-used-in-two-stages-but-is-defined-in-the-first-one-and-is-not-defined-in-the-second-one/41):
`Validation does not fail when a parameter is used in two stages but is defined in the first one and is not defined in the second one`
To reproduce the issue and test on `reana-demo-root6-roofit` example:
- Add `myPar: 1` in [reana spec](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/reana-yadage.yaml#L11)
- Define `myPar` in [`gendata` stage](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/workflow/yadage/workflow.yaml#L23): ```myPar: {step: init, output: myPar}```
- Use it in [`gendata` stage](https://github.com/reanahub/reana-demo-root6-roofit/blob/master/workflow/ya …

validate: map steps in yadage parameter validation

---

setup.py

Due to dropping python 2 support in version 0.2.4
https://pypi.org/project/ruamel.yaml.clib/0.2.4/
Build logs with current master: https://github.com/mvidalgarcia/reana-client/runs/2912479360?check_suite_focus=true
```
Collecting ruamel.yaml.clib==0.2.4                                                                                                                                                                                                                            
Downloading ruamel.yaml.clib-0.2.4.tar.gz (180 kB)                                                                                                                                                                                                          
|████████████████████████████████| 180 kB 3.7 MB/s …
```

setup: upper pin `ruamel.yaml.clib` for py2

---

reana_client/api/client.py
reana_client/cli/workflow.py
reana_client/config.py
reana_client/utils.py
reana_client/validation/parameters.py
setup.py

closes #531
```console
$ reana-client create -f reana-snakemake.yaml -w helloworld-snakemake
$ reana-client upload -w helloworld-snakemake
$ reana-client start -w helloworld-snakemake
$ reana-client logs -w helloworld-snakemake                       
==> Workflow engine logs
2021-07-22 09:16:27,199 | reana-workflow-engine-snakemake | MainThread | INFO | Snakemake workflows are not yet supported. Skipping...
2021-07-22 09:16:27,199 | reana-workflow-engine-snakemake | MainThread | INFO | Workflow spec received: workflow/snakemake/Snakefile
2021-07-22 09:16:27,211 | root | MainThread | INFO | Workflow 1d297776-64de-4ee9-8e32-78b34cbe45b4 finished. Files available at users/00000000-0000-0000-0000-000000000000/workflows/1d297776-64de-4ee9-8e32-78b34cbe45b4.
```

snakemake: load reana spec to send it to server

---

CHANGES.rst
reana_client/cli/files.py
reana_client/schemas/reana_analysis_schema.json

closes https://github.com/reanahub/reana-client/issues/536
Tested `roofit` demo with:
```yaml
outputs:
files:
- results/data.root
- results/plot.png
directories:
- results
- code
```
result:
```yaml
- results/data.root
- results/plot.png
- download_roofit.1_code_2021-07-12-100149.zip
- download_roofit.1_results_2021-07-12-100148.zip
```

reana.yaml: add support for outputs.directories

---

reana_client/api/client.py
reana_client/validation/environments.py
setup.py

closes #540
Supersedes https://github.com/reanahub/reana-client/pull/542
```console
$ cd ../reana-demo-root6-roofit   # test also helloworld & worldpopulation
$ reana-client validate --environments -f reana-snakemake.yaml --pull
==> Verifying REANA specification file... /Users/marco/code/reanahub/reana-demo-root6-roofit/reana-snakemake.yaml
-> SUCCESS: Valid REANA specification file.
==> Verifying REANA specification parameters... 
-> SUCCESS: REANA specification parameters appear valid.
==> Verifying workflow parameters and commands... 
-> SUCCESS: Workflow parameters and commands appear valid.
==> Verifying dangerous workflow operations... 
-> SUCCESS: Workflow operations appear valid.
==> Verifying environments in REANA specification file...
-> SUCCESS: Environment image …
```

snakemake: add environment validation

---

reana_client/cli/cwl_runner.py

This PR removes legacy Python2 support (dropped in the upcoming `0.8.0` release) from the `cwl_runner.py` module.
In addition, unused imports have been cleaned up.

cwl: remove legacy Python2 support

---

.github/workflows/ci.yml

Right now CI is not passing in multiple PRs, because of the `graphviz` issues. 
Please have a look into https://github.com/reanahub/reana-client/pull/550/checks?check_run_id=3518962084 for error log.
This PR will fix this issue by installing some system dependencies for `graphviz` support.

ci: added system dependencies for graphviz support

---

AUTHORS.rst
reana_client/schemas/reana_analysis_schema.json
reana_client/utils.py

Closes reanahub/reana-client#562

validate: add validate-sections to validate misspelled directives or directives in reana.yaml

---

AUTHORS.rst
setup.py

Add `python_requires` of `>=3.6` to ensure that installs from PyPI coming from users on **Python 2** get the last release that still had Python 2 support and not a broken (for Python 2) release with Python 3 only syntax.

build: Require python >= 3.6 for install

---

CHANGES.rst
reana_client/api/client.py
reana_client/cli/utils.py
reana_client/cli/workflow.py
reana_client/utils.py
setup.py
tests/test_cli_workflows.py

closes https://github.com/reanahub/reana-client/issues/584
To test make sure it works:
- using `reana-client`:
```
$ reana-client create -w test.41
==> ERROR: Workflow name test.41 contains illegal character "."
```
- [using Python API](https://blog.reana.io/posts/2021/reana-client-python-api/)

api: validate workflow name in create_workflow_from_json

---

CHANGES.rst
MANIFEST.in
scripts/create-appimage.sh

Adds script that creates reana-client standalone AppImage executables.
Closes #390.

scripts: create standalone AppImage executables

---

reana_client/version.py

[Demos' CI fails](https://github.com/reanahub/reana-demo-root6-roofit/actions/runs/1738526767) because we have some [breaking changes in a reana-commons import](https://github.com/reanahub/reana-client/commit/7f9dc7e262ecc6584275744d7e11f3651aacdaea#diff-4f20d18bf32c181d09b016a6a363171402d113bb01347de15da4768afcbe6998R30) that are not included in the reana-client release.
We need to release a new version so `reana-client validate` works again when is installed by [the GitHub Action](https://github.com/reanahub/reana-github-actions/blob/7e99bef6ad58bc352a54978156f6aa73bc08ebb3/local-validate/action.yml#L21).

release: 0.8.1a2

---

CHANGES.rst
reana_client/cli/workflow.py
tests/test_cli_workflows.py

The `run` and `start` commands of reana-client have a `--follow` option to follow the execution of the workflow until termination.
However, the command stops as soon as the workflow is queued, without waiting for the end of the execution:
```console
$ reana-client run --follow
==> Creating a workflow...
==> Verifying REANA specification file...
-> SUCCESS: Valid REANA specification file.
==> Verifying REANA specification parameters... 
-> SUCCESS: REANA specification parameters appear valid.
==> Verifying workflow parameters and commands... 
-> SUCCESS: Workflow parameters and commands appear valid.
==> Verifying dangerous workflow operations... 
-> SUCCESS: Workflow operations appear valid.
==> Verifying compute backends in REANA specification file...
-> SUCCESS: Workflow compute …
```

cli: fix `--follow` option

---

reana_client/config.py
reana_client/validation/environments.py

Docker registry v1 API is deprecated: https://www.docker.com/blog/registry-v1-api-deprecation/
and seems to be missing some of the data:
```
https://index.docker.io/v1/repositories/reanahub/reana-env-root6/tags/6.18.04 <-- works
https://index.docker.io/v1/repositories/reanahub/reana-env-aliphysics/tags/vAN-20180614-1 <-- does not work
```
Using the new registry v2 API both cases works fine:
```
https://hub.docker.com/v2/repositories/reanahub/reana-env-root6/tags/6.18.04
https://hub.docker.com/v2/repositories/reanahub/reana-env-aliphysics/tags/vAN-20180614-1
```
PR also fixes an issue found while trying to get docker image UID. Gist of the issue is here:
```
docker run -i -t --rm reanahub/reana-env-root6:6.18.04 sh -c "/usr/bin/id -u" --> 0
docker run -i -t --rm …
```

validation: switch to docker registry v2 API for environments validation

---

CHANGES.rst
reana_client/cli/files.py
setup.py
tests/conftest.py
tests/test_cli_files.py

Now `reana-client upload` command will respect `.gitignore` files.
Expected behavior:
- upload all `input.files`, ignore `.gitignore` in this case;
- upload all files or directories from `input.directories` that are not matched by `.gitignore`; 
- empty directories will not be uploaded
How to test:
1. Go to the `reana-demo-atlas-recast` example.
2. Create a `.gitignore` file there with the following content:
```
do-not-upload-*/
*.py[cod]
```
3. Go to the `workflow/` directory. Create files that will be ignored:
```bash
echo "Hello" > some_python.pyc
mkdir do-not-upload-me
echo "World" > do-not-upload-me/text.txt
```
4. Run example (with `run`), you can see that files that match `.gitignore` are not uploaded.
5. Check if reana-client works as before when `.gitignore` doesn't exist. …

files: respect gitignore when uploading files

---

AUTHORS.rst
CHANGES.rst
reana_client/cli/utils.py
reana_client/cli/workflow.py
tests/test_cli_workflows.py

Desired behavior for this PR:
```bash
$ reana-client list  # do not show deleted workflows, show all other statuses
$ reana-client list --show-deleted-runs  # shows deleted workflows and all other statuses
$ reana-client list --all  # shows deleted workflows and all other statuses
$ reana-client list --filter name=myworkflow  # show workflows that match the name, do not show deleted workflows if any
$ reana-client list --filter name=myworkflow  --show-deleted-runs  # show workflows that match the name, show deleted workflows if any
$ reana-client list --filter status=deleted  # show deleted workflows, no need to use  "--show-deleted-runs"
```
How to test:
- check that PR behaves in the desired way
closes #612

cli: add --show-deleted-runs option to list command

---

CHANGES.rst
reana_client/cli/workflow.py
reana_client/utils.py
tests/test_cli_workflows.py
tests/test_utils.py

Closes #616 
How to test:
1. Execute and create some workflows
2. Run `reana-client list --include-duration`
3. Run `reana-client list --include-duration --sort duration`
4. Run `reana-client status -w workflow --include-duration`
Expected result: the durations of the workflows are correctly displayed and the entries are sorted in the right order

cli: add option to show workflow duration to `list` and `status` commands

---

.github/workflows/ci.yml
reana_client/cli/workflow.py
tests/test_cli_workflows.py

Closes #629
How to test:
1. Create a new demo workflow: `reana-client create -w test`
2. Start the workflow without uploading inputs: `reana-client start -w test --follow`
Expected result: the workflow fails because of missing files and reana-client prints `==> ERROR: test has been failed`

workflow: show error when workflow fails after `start`

---

reana_client/cli/files.py

After introducing [missing workflow spec schema to get_workflow_specification endpoint](https://github.com/reanahub/reana-server/pull/549), reana-client started to include and set all the missing properties to `None` in the response of this endpoint. This affected `upload` and `download` commands since internally this endpoint is used to retrieve the spec and get the files to upload/download. This PR fixes this issue

cli: improve how reana spec is handled in `download` and `upload` commands

---

CHANGES.rst
reana_client/cli/workflow.py
tests/test_cli_workflows.py

workflow: always upload REANA specification on create and restart

---

reana_client/cli/workflow.py
tests/test_cli_workflows.py

When opening an interactive session with the `open` command, the user is now notified about the maximum inactivity time before the session is automatically closed, if the autoclosure was enabled by the REANA administrators.
Closes #657

workflow: add message about autoclosure of the interactive session.

---

.github/codecov.yml

Adds desired targets and threshold values for code coverage tests in pull requests.
Removes custom code coverage range to fall back to codecov defaults.

codecov: add threshold values

---

CHANGES.rst
reana_client/validation/utils.py
setup.py

utils: display warning messages about REANA spec validation

---

CHANGES.rst
reana_client/api/client.py
setup.py
tests/conftest.py
tests/test_cli_workflows.py

Amend `create_workflow_from_json` so that the workflow specification is
always loaded in the REANA specification that is passed to reana-server.
Closes #666.

api: fix create_workflow_from_json to load workflow specification

---

CHANGES.rst
reana_client/cli/workflow.py
tests/conftest.py
tests/test_cli_workflows.py

cli: fix `run` command when specification does not contain `inputs`

---

reana_client/validation/utils.py
setup.py

Change the warning message generated when unexpected properties are
found in the REANA specification during the validation phase to include
the path to the invalidating properties.
Closes #679.

validation: improve warning message for unexpected properties

---

scripts/create-appimage.sh

Fixes AppImage building procedure by upgrading to Python 3.8.18.

build(appimage): upgrade to Python 3.8.18

---

setup.py
tests/test_cli_workflows.py

After upgrading Snakemake to version 7.32.4 (reanahub/reana-commons#435)
there is no need to avoid running Snakemake tests on Python 3.11 and
3.12, as it should be supported.
Closes #655

test(snakemake): allow running Snakemake 7 tests on Python 3.11+ (#700)

---

.commitlintrc.yaml
.github/workflows/ci.yml
.gitignore
Dockerfile
MANIFEST.in
run-tests.sh

Usage example:
```console
$ cd reana-demo-root6-roofit
$ export REANA_SERVER_URL=https://reana.cern.ch
$ export REANA_ACCESS_TOKEN=xxxxxxxxxxxxxxxxxxx
$ docker pull docker.io/reanahub/reana-client:0.9.3
$ docker run -i -t --rm -v $PWD:/home/reana \
--env REANA_SERVER_URL --env REANA_ACCESS_TOKEN \
docker.io/reanahub/reana-client:0.9.3 run -w test
```
Closes #709

build(docker): create `reana-client` container image

---

AUTHORS.md
reana_client/cli/workflow.py

Fix typo that I spotted during the demo this morning.

docs(cli): fix `open` command documentation typo (#716)

---

.github/workflows/ci.yml
reana_client/utils.py
setup.py
tests/test_utils.py

BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784

build(python): drop support for Python 3.6 and 3.7 (#715)

---

.github/workflows/ci.yml
pyproject.toml
run-tests.sh
setup.cfg
setup.py
tox.ini

- **ci(pytest): invoke `pytest` directly instead of `setup.py test` (#725)**
- **build(python): remove deprecated `pytest-runner` (#725)**
- **build(python): use optional deps instead of `tests_require` (#725)**
- **build(python): add minimal `pyproject.toml` (#725)**
Closes https://github.com/reanahub/reana/issues/814

deprecations setuptools

---

tox.ini

Fixes `tox` configuration with respect to installing all optional package dependencies that are necessary for running various tests.
Fixes `tox` collecting of code coverage information by forcing editable mode also in the test running instructions.

ci(tox): fix collecting code coverage information

---

.github/workflows/ci.yml
AUTHORS.md
reana_client/cli/workflow.py

Pin `setuptools` to the maximum version of 70 to allow working on Ubuntu 20.04 LTS based environments. (New versions of `setuptools` are not compatible.)
Note that this fix is necessary only for the `maint-0.9` branches and the REANA 0.9 release series. In `master` we have switched to Ubuntu 24.04 LTS based environments and Python 3.12 and no pinning is necessary there.

ci(actions): pin setuptools 70

---

AUTHORS.md
Dockerfile
docs/cmd_list.txt
reana_client/api/client.py
reana_client/cli/__init__.py
reana_client/cli/workflow.py
reana_client/config.py
setup.py
tests/test_cli_workflows.py

Adds new `--shared`, `--shared-by`, and `--shared-with` arguments to the
`list` CLI command to display workflows along with their sharing
information.
Closes #687

cli: implement list --shared argument

---

AUTHORS.md
docs/cmd_list.txt
reana_client/cli/__init__.py
reana_client/cli/files.py
reana_client/cli/test.py
tests/test_cli_files.py
tests/test_cli_test.py

feat(test): implement test command

---

.github/workflows/ci.yml
reana_client/api/client.py
reana_client/api/utils.py
setup.py
tests/test_api_utils.py
tox.ini

Closes https://github.com/reanahub/reana/issues/837
Add support for Python 3.13.
Replaced `cgi.parse_headers` with `email.message.Message` as recommended in https://peps.python.org/pep-0594/#cgi. Added test to make sure it does the same things that the previous code did. Also tested as in https://github.com/reanahub/reana-client/pull/490.

build(python): add support for Python 3.13 (#732)

---

AUTHORS.md
reana_client/cli/utils.py
reana_client/cli/workflow.py
reana_client/config.py
tests/test_cli_workflows.py

Closes https://github.com/reanahub/reana-client/issues/730
Old code is moved to `retrieve_workflow_logs` function, log following implemented in `follow_workflow_logs`.
Added test for the command (both retrieval and following).

feat(cli): add --follow flag to logs command (#729)

---

.github/workflows/ci.yml
reana_client/api/client.py
reana_client/api/utils.py
setup.py
tests/test_api_utils.py
tox.ini

build(python): add support for Python 3.13 (#736)

---

.github/workflows/ci.yml

Updates CI runners to use Ubuntu 22.04 in the `maint-0.9` branches because 20.04 is not supported anymore. Also removes Python 3.6 from the test matrix because the runners do not support it anymore.

ci(runners): upgrade CI runners to Ubuntu 22.04
