- CONTRIBUTING.rst
> docs: fix link to repo's issues

- docs/conf.py
- docs/gettingstarted.rst
- docs/index.rst
- docs/installation.rst
- reana_client/api/__init__.py
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/ping.py
- reana_client/config.py
- setup.py
- tests/test_cli_ping.py
> cli: add CLI skeleton and simple API client module

- MANIFEST.in
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/analyses.py
- reana_client/config.py
- reana_client/openapi_connections/reana_server.json
- setup.py
* Adds Bravado for automatic OpenAPI client generation.
> cli: add list and create workflows

- .travis.yml
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/analyses.py
- reana_client/config.py
- reana_client/openapi_connections/reana_server.json
- reana_client/schemas/reana_analysis_schema.json
- reana_client/utils.py
- setup.py
> cli: submit spec file instead of url

- docs/gettingstarted.rst
* According to #22, full list of commands has been added.
* (Closes #25).
> docs: add CLI skeleton to documentation

- .gitignore
- MANIFEST.in
- pycharm_click_debug.py
- reana_client/cli/__init__.py
- reana_client/cli/analyses.py
- reana_client/cli/inputs.py
- reana_client/cli/namesgenerator.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- setup.py
* Change cli syntax and structure to use new style commands
(see #22)
(closes #27)
> cli: amend syntax and structure of cli

- reana_client/cli/__init__.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- reana_client/config.py
- setup.py
* Add `inputs list` command
(closes #30)
* Add `workflow status` command
(closes #29)
* Add `outputs list` and `outputs download` commands
(closes #28)
> cli: add new commands

- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/openapi_connections/reana_server.json
> cli: add workflow create

- reana_client/api/client.py
- reana_client/cli/analyses.py
- reana_client/cli/inputs.py
- reana_client/cli/namesgenerator.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/openapi_connections/reana_server.json
* reactivate workflow list command.
* use organization and user to `workflow list`.
* small naming fixes to make things more consistent.
> cli: reactivate workflow list command

- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/openapi_connections/reana_server.json
* Add status command to get status of previously created workflow
(closes #39)
> cli: add status command

- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/openapi_connections/reana_server.json
> api: add start_analysis command

- reana_client/utils.py
- setup.py
> utils: import fix

- reana_client/api/client.py
- reana_client/cli/outputs.py
- reana_client/openapi_connections/reana_server.json
> cli: add download output file command

- docs/cliapi.rst
- docs/conf.py
- docs/index.rst
- reana_client/api/__init__.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- setup.py
* Adds CLI API documentation by means of `sphinx-click` extension.
> docs: CLI API

- reana_client/api/client.py
- reana_client/cli/outputs.py
- reana_client/openapi_connections/reana_server.json
> cli: add list workflow outputs command

- reana_client/api/client.py
- reana_client/cli/inputs.py
- reana_client/openapi_connections/reana_server.json
> cli: add list workflow inputs command

- docs/developerguide.rst
- docs/gettingstarted.rst
- docs/index.rst
- docs/userguide.rst
* Completes "Getting started" documentation and starts "User guide" and
"Developer guide".
> docs: user and developer guide improvements

- CHANGES.rst
- reana_client/version.py
> release: v0.1.0

- reana_client/version.py
> version: post-release bump

- reana_client/cli/analyses.py
- reana_client/cli/inputs.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
> cli: change logging mode for errors and print richer info

- .gitignore
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/analyses.py
- reana_client/cli/cwl_runner.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- reana_client/openapi_connections/reana_server.json
- reana_client/utils.py
- setup.py
- tests/test_cli_ping.py
* Squashed version of https://github.com/reanahub/reana-client/pull/36
> cwl: initial integration

- reana_client/cli/__init__.py
- reana_client/cli/analyses.py
- reana_client/cli/code.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
* (closes #72)
* Prettifies commands outputs.
> cli: less verbosity

- docs/gettingstarted.rst
- reana_client/cli/code.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
* Changes the `--output-format,  -of` flag to `--json`
(Closes https://github.com/reanahub/reana-client/issues/74)
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
> cli: change in output_format flag

- reana_client/api/client.py
- reana_client/cli/analyses.py
- reana_client/cli/code.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
- reana_client/openapi_connections/reana_server.json
* Standardizes the way of catching `Bravado` exceptions so appropiate
messages are show to the user (addresses #83).
> cli: improve end user messages on error scenarios

- reana_client/cli/cwl_runner.py
* fixes file uploading for conformance test
"Test that workflow defaults override tool defaults"
> cwl-runner: fixes & enhancements for full CWL conformance

- setup.py
> installation: upgrade yadage

- reana_client/api/client.py
- reana_client/cli/cwl_runner.py
* Fixes CWL test runner following up the recent changes related to the
persistent workflow names.
> cli: CWL runner fixes

- reana_client/cli/code.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- reana_client/utils.py
> global: $REANA_WORKON -> REANA_WORKON

- reana_client/cli/code.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- reana_client/utils.py
> cli: tab separated output

- docs/developerguide.rst
- docs/gettingstarted.rst
- docs/requirements.txt
- docs/userguide.rst
* Updates documentation for the forthcoming REANA v0.2.0 release.
* Fixes ReadTheDocs documentation generation by providing custom
`docs/requirements.txt` file to install necessary Sphinx packages.
> docs: general update for v0.2.0 release

- docs/gettingstarted.rst
- docs/userguide.rst
- reana_client/cli/status.py
* Adds documentation for the ``status`` command.
* Fixes two ``reana-client`` command invocations in the Getting Started guide.
> docs: improvements

- AUTHORS.rst
- reana_client/version.py
> docs: author ORCID links

- reana_client/cli/workflow.py
- reana_client/openapi_connections/reana_server.json
- reana_client/schemas/reana_analysis_schema.json
- reana_client/utils.py
> openapi: reana-server spec with progress in status

- reana_client/api/client.py
Closes https://github.com/reanahub/reana-client/issues/69
> client: fix download traceback

- reana_client/cli/__init__.py
> cli: better server defaults

- reana_client/cli/ping.py
- reana_client/cli/workflow.py
* Changes the way active workflow run is highlighted (closes #114).
* Fixes listing workflows error when there is not workoon selected
(closes #117).
> cli: fix workflow list when no workon provided

- reana_client/cli/workflow.py
> cli: remove command column if not present

- reana_client/api/client.py
- reana_client/cli/users.py
- reana_client/openapi_connections/reana_server.json
> cli: remove register method

- reana_client/utils.py
> cli: decrease verbosity of cwl workflow creation

- reana_client/api/client.py
- reana_client/cli/code.py
- reana_client/cli/inputs.py
- reana_client/cli/outputs.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/openapi_connections/reana_server.json
> cli: renaming REANA_TOKEN -> REANA_ACCESS_TOKEN

- reana_client/api/client.py
- reana_client/cli/cwl_runner.py
- reana_client/cli/files.py
- reana_client/cli/status.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/openapi_connections/reana_server.json
Connects https://github.com/reanahub/reana-commons/issues/25
> global: remove organization

- reana_client/cli/workflow.py
- reana_client/schemas/reana_analysis_schema.json
> schemas: optional parameters field in reana.yaml

- reana_client/cli/workflow.py
Connect https://github.com/reanahub/reana-commons/issues/24
> cli: progress changes after workflow run merge

- reana_client/cli/workflow.py
* Fixes bug reported in https://github.com/reanahub/reana-workflow-controller/pull/116
Connect https://github.com/reanahub/reana-commons/issues/24
> cli: fix getting total number of jobs

- reana_client/cli/workflow.py
> cli: refactor workflow status

- reana_client/api/client.py
- reana_client/cli/cwl_runner.py
> files: fix ROOT file upload

- reana_client/cli/__init__.py
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
- reana_client/decorators.py
* Introduces a decorator to be added to the commands that need
an API client (closes #153).
> cli: initialise API client at command level

- CHANGES.rst
- docs/developerguide.rst
- docs/gettingstarted.rst
- docs/requirements.txt
- docs/userguide.rst
- reana_client/cli/ping.py
- reana_client/version.py
- requirements-dev.txt
- setup.py
> global: release checklist

- reana_client/cli/workflow.py
- reana_client/utils.py
Connects https://github.com/reanahub/reana-workflow-engine-serial/issues/34.
Depends on https://github.com/reanahub/reana-commons/pull/40.
> validate: check if workflow parameters are expandable 

- reana_client/openapi_connections/reana_server.json
* Harmonises date time format (closes #162).
> openapi: updates to latest REANA Server

- reana_client/__init__.py
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/cwl_runner.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
- reana_client/decorators.py
- reana_client/version.py
> docs: document serial CACHING parameter

- reana_client/cli/workflow.py
Connects https://github.com/reanahub/reana-workflow-engine-serial/issues/40
> cli: rename parameter CACHING>CACHE in docstring

- docs/developerguide.rst
- docs/gettingstarted.rst
- docs/userguide.rst
* Adds more advice regarding access tokens for user scenarios.
* Amends usage example.
* Fixes instructions on how to install developer version.
> docs: more advice on access tokens

- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/files.py
> cli: resolve symlinks and upload hard copy

- reana_client/cli/files.py
- reana_client/schemas/reana_analysis_schema.json
* Adds directories as input property for reana.yaml files.
* Removes code input property.
Closes #171 
> schemas: addition of input directories

- .travis.yml
- setup.py
* Upgrades cwltool since current pinned version breaks with
Python 3.7 (closes #169).
> installation: upgrade cwltool

- reana_client/cli/files.py
* Uploads all input files and directories defined in the reana.yaml.
Closes #172 
> cli: upload input files

- reana_client/api/client.py
- reana_client/cli/cwl_runner.py
- reana_client/cli/files.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- reana_client/decorators.py
* Updated the out of sync `cwl-runner` CLI to use latest API (closes #178).
* Removes unnecessary custom functions to discover file dependencies (closes #147).
>  cwl-runner: upgrade to latest client API

- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/utils.py
- setup.py
* Renames reana_spec to reana_specification to match the latest
reana-server api parameter.
Connects https://github.com/reanahub/reana-db/issues/12
> api: reana_specification parameter

- docs/developerguide.rst
- docs/gettingstarted.rst
(connects #106)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> docs: virtualenv instead of mkvirtualenv

- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/utils.py
- reana_client/decorators.py
- setup.py
- tests/conftest.py
- tests/test_cli_files.py
- tests/test_cli_ping.py
- tests/test_cli_workflows.py
> instalation: updates pytest and pytest-reana

- AUTHORS.rst
- CHANGES.rst
- reana_client/version.py
- setup.py
- tests/conftest.py
> release: v0.4.0

- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/utils.py
- setup.py
- tests/test_cli_workflows.py
* Introducing new flag for `start` command to override workflow
input parameters. Closes #200
> 200 override start parameters

- reana_client/cli/files.py
* Improves cli flags and help messages.
(cherry picked from commit 55e64a1f5445fed4b3871f3db56cc026ca41468b)
> cli: minor flag and output message fixes

- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/workflow.py
- tests/test_cli_files.py
* ADDS cli and api command for deleting workflow runs,
with option for deleting all runs of a given workflow.
Closes #192 
> global: workflow deletion

- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/workflow.py
- setup.py
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
Connects #194.
> cli: add stop command

- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/cli/workflow.py
- reana_client/errors.py
- tests/test_cli_files.py
* Closes #210.
Blocked by https://github.com/reanahub/reana-commons/pull/69.
> cli: add delete files command

- reana_client/utils.py
(cherry picked from commit ea704b013321a3e0104b5300bce5c7e52d725aee)
> cli: operational options fix

- reana_client/utils.py
* Fixes CWL workflow format, which will be saved in DB.
Connects reanahub/reana-workflow-engine-cwl/issues/75
> utils: fix CWL workflow format

- docs/apidocs.rst
- docs/index.rst
- reana_client/api/client.py
- reana_client/config.py
- tests/test_cli_workflows.py
* Adding new feature which allows to create a workflow form
json. Connects #228
> client: allows workflow creation from json

- reana_client/api/client.py
Co-authored-by: Rokas Maciulaitis <rokas.maciulaitis@cern.ch>
> api: add missing intermediary specification key

- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/workflow.py
- setup.py
- tests/test_cli_workflows.py
* (connect reanahub/reana-workflow-controller#178).
> cli: add open interactive processes command

- reana_client/schemas/reana_analysis_schema.json
- setup.py
* Adds resources field in reana analysis schema.
Connects https://github.com/reanahub/reana-cluster/issues/154
> schemas: addition of resources field

- docs/gettingstarted.rst
- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/files.py
- tests/test_cli_files.py
> cli: adding mv command

- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/version.py
- setup.py
- tests/test_cli_workflows.py
* Adds command to display workspace disk usage.
Displays workspace tree with disk usage for each element by default,
'-s/--summarize' parameter shows only total sum.
Values shown in human readable format.
Closes #238 
> cli: workspace disk usage

- reana_client/version.py
- setup.py
> installation: reana-commons with kubernetes

- reana_client/cli/workflow.py
Connects reanahub/reana-workflow-controller#184.
> cli: show link to protected interactive session

- reana_client/cli/files.py
- reana_client/cli/workflow.py
> cli: removing duplicated error msg

- reana_client/schemas/reana_analysis_schema.json
> json_schema: adding cvmfs repo validation

- reana_client/api/client.py
- reana_client/cli/workflow.py
- setup.py
- tests/test_cli_workflows.py
Closes https://github.com/reanahub/reana-client/issues/258.
> interactive-execution: use closed session types

- reana_client/api/client.py
- reana_client/cli/workflow.py
- tests/test_cli_workflows.py
> cli: allows to close an interactive session

- reana_client/api/client.py
- reana_client/cli/workflow.py
- reana_client/utils.py
- setup.py
- tests/test_cli_workflows.py
> cli: new command for listing interactive sessions

- docs/userguide.rst
- reana_client/cli/cwl_runner.py
- reana_client/utils.py
- setup.py
- tests/test_cli_workflows.py
> docs: ineractive session userguide.

- docs/userguide.rst
> docs: renaming workflows cmd to list

- reana_client/cli/__init__.py
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
> cli: grouping commands by functionality

- reana_client/cli/utils.py
- reana_client/cli/workflow.py
* Interacvtive sessions list command `list --sessions` shows
access token in uri column. Closes #271
> cli: interactive sessions list show token

- MANIFEST.in
- docs/userguide.rst
- reana_client/cli/__init__.py
- reana_client/config.py
> docs: rendering fixes

- docs/cliapi.rst
- docs/cmd_list.txt
- reana_client/cli/__init__.py
- run-tests.sh
> docs: adding commands summary from `--help`

- reana_client/cli/files.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- reana_client/config.py
- tests/test_cli_files.py
- tests/test_cli_workflows.py
* Adding decorator function for passing `workflow` option
from CLI.
> cli: workflow option as decorator

- CHANGES.rst
- README.rst
- docs/cmd_list.txt
- docs/conf.py
- reana_client/cli/workflow.py
- reana_client/version.py
- setup.py
> release: v0.5.0

- docs/cmd_list.txt
- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/secrets.py
- reana_client/utils.py
- setup.py
- tests/test_cli_secrets.py
* Closes #283
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> cli: implement a user secrets management mechanism

- reana_client/utils.py
- tests/test_cli_secrets.py
* Allow adding secret from literal containing '=' (Closes #290)
> cli: fix secret from literal parsing

- reana_client/api/client.py
- tests/test_cli_secrets.py
* Raise the correct exception after trying to add secret that already exists.
* Closes #289
Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>
> cli: fix secret that already exists exception

- reana_client/cli/workflow.py
Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>
> doc: add space between flags on example command

- reana_client/api/utils.py
- reana_client/cli/files.py
- reana_client/cli/workflow.py
- reana_client/config.py
- tests/test_cli_files.py
Add new flag to the list workspace files command.
Allow user to retrieve files' URLs
Closes #297
Signed-off-by: leticia <leticia.farias.wanderley@cern.ch>
> cli: add flag to list output URLs

- docs/userguide.rst
> docs: HTCondorCERN backend usage

- docs/cmd_list.txt
- reana_client/cli/ping.py
- reana_client/version.py
> cli: new ``version`` command

- AUTHORS.rst
- reana_client/utils.py
- setup.py
* Closes #74
Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>
> cwl: upgrade

- setup.py
* Addresses reanahub/reana-client#320.
> installation: jsonschema from REANA-Commons

- reana_client/api/client.py
- tests/test_cli_files.py
* Abandons Bravado for file uploads striving for high performance
(closes #302).
> client: file uploads with Requests

- reana_client/cli/files.py
- reana_client/cli/secrets.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- tests/test_cli_files.py
- tests/test_cli_secrets.py
- tests/test_cli_workflows.py
> cli: moves access token check to callback function

- reana_client/cli/utils.py
> cli: updates callback function signature

- reana_client/cli/__init__.py
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/secrets.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- tests/test_cli_workflows.py
> cli: centralises API client configuration check

- docs/userguide.rst
* Addresses reanahub/reana-job-controller/issues/71
> docs: reanmes HTCONDORCERN* vars to CERN*

- reana_client/cli/__init__.py
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/secrets.py
- reana_client/cli/workflow.py
- setup.py
* No need to check connection for every command (validate, version)
> cli: refactors connection check

- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/cli/workflow.py
- setup.py
> cli: enrich disk usage output format

- reana_client/api/client.py
- reana_client/utils.py
addresses reanahub/reana-client#350
> cli: fix typos and warnings

- reana_client/cli/files.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
* Addresses reanahub/reana-client/issues/349
> cli: renames filter flag to format

- docs/userguide.rst
- reana_client/api/client.py
- reana_client/cli/workflow.py
> cli: adds rerun flag for start command

- reana_client/cli/workflow.py
- tests/test_cli_workflows.py
> cli: changes default sorting of list cmd by creation date

- docs/cmd_list.txt
- docs/userguide.rst
- reana_client/cli/workflow.py
- setup.py
* Allows to pass workflow specification
Closes reanahub/reana-workflow-controller/issues/289
> Move restart to separte cmd

- reana_client/cli/workflow.py
> cli: returns proper msg in case workflow does not exist

- reana_client/api/client.py
- reana_client/cli/workflow.py
> cli: adds option to get logs of a specific step

- reana_client/cli/workflow.py
- reana_client/version.py
- tests/test_cli_workflows.py
* Adds new columns to report workflow start and finished times
(closes #370).
> cli: status and list with start/finished times

- reana_client/cli/utils.py
- reana_client/cli/workflow.py
* Modeled after brew and archlinux log styles (closes #371).
> logs: format logs with marks and colors

- reana_client/cli/workflow.py
> cli: modifies error msg

- reana_client/api/client.py
- reana_client/cli/ping.py
- setup.py
- tests/test_cli_ping.py
> cli: validate token and prettify output for ping

- MANIFEST.in
- reana_client/cli/files.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/utils.py
- tests/test_cli_workflows.py
> cli: accept reana.yml spec filename

- reana_client/cli/utils.py
- reana_client/cli/workflow.py
> cli: forbid dot in workflow name on run

- .gitignore
- MANIFEST.in
- run-tests.sh
- scripts/generate_cli_api.py
closes reanahub/docs.reana.io#22
> docs: add script to generate cli api docs

- .travis.yml
- CHANGES.rst
- README.rst
- docs/conf.py
- pytest.ini
- reana_client/__init__.py
- reana_client/api/client.py
- reana_client/api/utils.py
- reana_client/cli/__init__.py
- reana_client/cli/cwl_runner.py
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/secrets.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/utils.py
- run-tests.sh
- scripts/generate_cli_api.py
- setup.py
- tests/conftest.py
- tests/test_cli_files.py
- tests/test_cli_ping.py
- tests/test_cli_secrets.py
- tests/test_cli_workflows.py
- tests/test_version.py
> global: Black support

- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- tests/test_cli_files.py
- tests/test_cli_workflows.py
closes reanahub/reana-server#180
> cli: add pagination fields to workflow list cmd

- reana_client/cli/workflow.py
- setup.py
closes https://github.com/reanahub/reana-db/issues/89
> cli: display interactive session status in list

- reana_client/cli/utils.py
> cli: allow multiple --format column titles

- AUTHORS.rst
- docs/cmd_list.txt
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/quotas.py
> cli: add new command to show user quota usage

- reana_client/api/client.py
- reana_client/cli/workflow.py
> cli: get rid of hard deletion

- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/cli/quotas.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- setup.py
- tests/test_cli_files.py
- tests/test_cli_workflows.py
* Closes reanahub/reana-server#296.
> cli: add --human-readable to all file/quota cmds

- reana_client/api/client.py
- reana_client/cli/files.py
- setup.py
closes reanahub/reana-server#282
> cli: fix exception handling on file upload

- CHANGES.rst
- reana_client/cli/ping.py
- reana_client/version.py
- setup.py
> cli: enrich ping command with version information

- .flake8
- .github/workflows/ci.yml
- MANIFEST.in
- reana_client/api/client.py
- reana_client/cli/cwl_runner.py
- reana_client/cli/files.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- run-tests.sh
- setup.py
- tests/test_cli_workflows.py
addresses https://github.com/reanahub/reana/issues/456
> ci: added flake8 linter

- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/utils.py
- setup.py
> validate: warn about using non-tagged latest images

- docs/index.rst
- reana_client/api/client.py
Newly added functions:
- upload_to_server
- list_files
- get_workflow_status
Also, tried to make parameters descriptions more consistent
> docs: added more functions under rest API docs section

- reana_client/utils.py
- reana_client/validation.py
> validate: add serial parameters validation

- reana_client/utils.py
- reana_client/validation.py
- tests/test_validate_environments.py
> validate: warn about using non-tagged images for yadage workflows

- reana_client/utils.py
- reana_client/validation.py
> validate: warn user when inputs are missing

- reana_client/config.py
- reana_client/validation.py
- tests/test_validate_parameters.py
> validate: add serial workflow parameters test and check for dangerous operations

- reana_client/validation.py
- setup.py
Depends on https://github.com/reanahub/reana-client/pull/462
Closes reanahub/reana#248
> validate: add cwl environment validation 

- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/utils.py
- reana_client/validation.py
- setup.py
- tests/test_validate_environments.py
- tests/test_validate_parameters.py
- check local images
- prevent failure if the image exists locally or remotely
closes #474
closes #475
closes #463
> validate: make image discovery more flexible

- reana_client/validation.py
- tests/conftest.py
- tests/test_validate_parameters.py
closes #473
Tested  with:
- `reana-demo-root6-roofit`
- `reana-demo-cdci-crab-pulsar-integral-verification`
- `reana-demo-cms-h4l`
> validate: Add CWL parameters validation

- reana_client/validation.py
- tests/test_validate_parameters.py
> validate: verify possibly dangerous operations in CWL workflows

- reana_client/config.py
closes https://github.com/reanahub/reana-workflow-controller/issues/363
> cli: add new pending state

- CHANGES.rst
- reana_client/api/client.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- setup.py
- tests/test_cli_workflows.py
performance optimisations for list command
closes #510
> list: add --include-progress and --include-workspace-size

- reana_client/cli/workflow.py
- setup.py
> config: import compute backends from r-commons

- setup.py
> installation: unpin six

- reana_client/cli/files.py
> fix typo in example docstring

- reana_client/api/client.py
closes https://github.com/reanahub/reana-client/issues/500
> cli: silently skip upload_to_server if paths is a none-like object

- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- setup.py
- tests/test_cli_files.py
PR testing Instructions:
1. Checkout  branch 521 in `r-client`, `r-commons`, `r-workflow-controller` and `r-server`.
2. Redeploy the cluster.
Test commands
Tests Passing locally:
closes https://github.com/reanahub/reana-client/issues/521
> cli: add --filter option in ls command

- CHANGES.rst
- reana_client/cli/files.py
- reana_client/version.py
closes https://github.com/reanahub/reana/issues/512
> release: 0.8.0a2

- reana_client/cli/files.py
- tests/test_cli_files.py
> cli: add --filter option in du command

- reana_client/cli/cwl_runner.py
- setup.py
closes https://github.com/reanahub/reana-workflow-engine-cwl/issues/187
WIP, still many troubles when running CWL tests:
```
$ git clone https://github.com/common-workflow-language/common-workflow-language
$ cd common-workflow-language
$ pip install cwltest
$ ./run_test.sh RUNNER=reana-cwl-runner
```
> cwltool: upgrade to the latest version

- .github/workflows/ci.yml
- setup.py
And revert CI commit which was replaced with a fix in https://github.com/reanahub/reana-commons/pull/290
> installation: bump shared modules

- reana_client/schemas/reana_analysis_schema.json
- reana_client/utils.py
> snakemake: added workflow types enum

- docs/cmd_list.txt
- reana_client/api/client.py
- reana_client/cli/ping.py
- reana_client/cli/workflow.py
- reana_client/utils.py
- setup.py
- tests/test_cli_workflows.py
Closes reanahub/reana-client#546
> cli: add function to read available workspaces

- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/quotas.py
- reana_client/cli/secrets.py
- reana_client/cli/utils.py
- reana_client/cli/workflow.py
- reana_client/config.py
- reana_client/utils.py
- tests/test_cli_workflows.py
This PR harmonizes the utilization of `click.secho(...)` and `click.echo(click.style(...))`, to the former.
Throughout the codebase, there are many calls to [click.secho](https://click.palletsprojects.com/en/8.0.x/api/#click.secho), which provides an _styled_ echo functionality. This would be totally equivalent to calling `click.style` within a `click.echo` block, so any occurrences of the their concatenation have been replaced by [click.secho](https://click.palletsprojects.com/en/8.0.x/api/#click.secho) calls.
> cli: harmonize click styled echos

- reana_client/validation/environments.py
- setup.py
closes reanahub/reana-workflow-engine-snakemake#13
> snakemake: adapt env validation to fallback image

- CHANGES.rst
- reana_client/api/client.py
- reana_client/cli/workflow.py
- setup.py
Closes reanahub/reana-client#452
> workflow: add -w option to list command to filter the workflows retrieved

- reana_client/cli/workflow.py
Closes reanahub/reana-client#561
> validate: throw exit code 1 on ERROR while validating

- README.rst
- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/quotas.py
- reana_client/cli/workflow.py
- run-tests.sh
closes reanahub/docs.reana.io#104
> ci: revert back docs.reana.io CLI API check

- reana_client/cli/workflow.py
- reana_client/errors.py
- reana_client/utils.py
- reana_client/validation/compute_backends.py
- reana_client/validation/environments.py
- reana_client/validation/workspace.py
- setup.py
- tests/conftest.py
- tests/test_cli_workflows.py
- tests/test_validate_compute_backends.py
- tests/test_validate_server_capabilities.py
closes reanahub/reana-workflow-controller#424
> validation: add compute backend validation

- CHANGES.rst
- reana_client/version.py
- setup.py
> release: 0.8.1

- CHANGES.rst
- reana_client/api/client.py
- reana_client/cli/files.py
- reana_client/config.py
- tests/test_cli_files.py
> cli: add option to write files to stdout

- reana_client/cli/files.py
- tests/test_cli_files.py
> files: improve message when gitignore is detected

- reana_client/cli/quotas.py
- setup.py
closes https://github.com/reanahub/reana-client/issues/607
> cli: port quota resource usage util to r-commons

- CHANGES.rst
- reana_client/cli/files.py
- tests/test_cli_files.py
> files: respect .reanaignore file during upload

- CHANGES.rst
- reana_client/api/client.py
- reana_client/cli/workflow.py
> workflow: delete workspace by default

- reana_client/cli/ping.py
closes https://github.com/reanahub/reana-client/issues/627
To test please use the PR against dev or prod servers, it should work fine
> cli: hide empty values in `info` command

- CHANGES.rst
- reana_client/cli/files.py
- reana_client/cli/ping.py
- reana_client/cli/quotas.py
- reana_client/cli/secrets.py
- reana_client/cli/workflow.py
- tests/test_cli_files.py
Closes reanahub/reana-workflow-controller#469
Closes #630
> cli: allow moving files while workflow is running

- CHANGES.rst
- docs/cmd_list.txt
- reana_client/api/client.py
- reana_client/cli/__init__.py
- reana_client/cli/retention_rules.py
- tests/test_cli_retention_rules.py
> cli: add `retention-rules-list` command

- reana_client/version.py
- setup.py
> setup: pin swagger_spec_validator

- CHANGES.rst
- reana_client/version.py
- setup.py
- installation: bump shared modules
- release: 0.9.0
> release: 0.9.0

- reana_client/cli/cwl_runner.py
- reana_client/cli/workflow.py
- reana_client/utils.py
- setup.py
- tests/test_cli_ping.py
closes https://github.com/reanahub/reana-client/issues/649
> cli: modify delete command description about session deletion

- docs/cmd_list.txt
- reana_client/api/client.py
- reana_client/cli/files.py
- setup.py
- tests/test_cli_files.py
> Add prune command

- CHANGES.rst
- reana_client/cli/workflow.py
- tests/test_cli_workflows.py
> workflow: fix run_number and size sorting issue

- CHANGES.rst
- reana_client/cli/workflow.py
- tests/test_cli_workflows.py
> cli: allow sorting using uppercase column names

- reana_client/cli/workflow.py
> validate: show YAML parsing errors

- CHANGES.rst
- reana_client/version.py
- setup.py
> release 0.9.2

- reana_client/utils.py
- tests/test_utils.py
> fix(status): correctly display duration of stopped workflows (#701)

- run-tests.sh
- setup.py
Allow unconventional commit style for the chore release commits created by Release Please.
> ci(commitlint): allow release commit style
